version: '3'
services:
  db_01:
    image: postgres:16.0
    container_name: postgres1
    healthcheck:

  db_02:
    image: postgres:16.0
    container_name: postgres2
    healthcheck:

  backend1:
    image: backend1:1.0
    container_name: backend1
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    healthcheck:
    depends_on:

  backend2:
    image: backend2:1.0
    container_name: backend2
    healthcheck:
    depends_on:

  backend_test:
    build: ./backend-testing
    container_name: backend-test
    depends_on:

  mock_api:
    image: mock-api:latest
    container_name: mock-api
